title: SPATIAL COCO CERTH
logo: /assets/img/logo.png
description: here is what i want to see in my description!!!!
show_downloads: true
google_analytics:
#theme: jekyll-theme-minimal

# Navigation links
header_pages:
  - index.md
  - about.md
  - contact.md
  - intro.md
  - presentation.md
  - projects.md